[tools]
elixir = "1.19.5-otp-28"
erlang = "28.3"
node = '22'

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true

[env]
# Persist history of the IEx (Elixir) and erl (Erlang) shells
ERL_AFLAGS = "-kernel shell_history enabled"

[tasks.log]
run = '''
aws logs tail '/ecs/admin' --follow --profile $1
'''

[tasks.restart]
usage = '''
arg "profile" "AWS profile name" default="dev"
'''
run = '''
aws ecs update-service --cluster graasp-$usage_profile --service admin --force-new-deployment --profile $usage_profile
'''

[tasks.remote]
usage = '''
arg "profile" "AWS profile name" default="dev"
'''
run = [
    'aws sts get-caller-identity --profile $usage_profile',
    'aws ecs execute-command --cluster graasp-$usage_profile --task $(aws ecs list-tasks --cluster graasp-$usage_profile --service admin --query "taskArns[0]" --output text --profile $usage_profile) --container admin --command "/app/bin/admin remote" --interactive --profile $usage_profile'
]

[tasks.backend-dev]
alias = "server"
run = "mix phx.server"

[tasks.dev]
depends = ["backend-dev", "frontend-dev"]
description = "start the backend and frontend servers in development mode"

[tasks.frontend-build]
dir = "../client"
run = "pnpm build-prod && cp -r dist/* ../admin/priv/static/client/"
description = "Build the frontend from the sibling folder and copy it to the static assets"
