import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :admin, AdminWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Sentry configuration
config :sentry,
  # We do not set the DSN from a hard coded value so that it is possible to enable or disable it.
  # To enable, simply provide an env var `SENTRY_DSN`
  # To disable ensure no env var with `SENTRY_DSN` is set
  # dsn: "https://b4c2635dfa3bb58ad2cded33d1201e57@o244065.ingest.us.sentry.io/4509863475740672",
  # the commit SHA (GIT_SHA build arg) distinguishes builds made between two version bumps
  release:
    (case System.get_env("GIT_SHA") do
       sha when sha in [nil, ""] -> Mix.Project.config()[:version]
       sha -> "#{Mix.Project.config()[:version]}+#{String.slice(sha, 0, 7)}"
     end),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  # sample 20% of transactions
  traces_sample_rate: 0.2,
  integrations: [
    telemetry: [
      report_handler_failures: true
    ]
  ]

config :admin, :logger, [
  {:handler, :sentry_handler, Sentry.LoggerHandler,
   %{
     config: %{
       metadata: [:file, :line],
       rate_limiting: [max_events: 10, interval: _1_second = 1_000],
       capture_log_messages: true,
       level: :error
     }
   }}
]

config :admin, Admin.SentryFilter, keep_db_spans: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
